name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies for frontend
      working-directory: ./docker_compose/frontend
      run: |
        npm install --legacy-peer-deps
        npm audit fix

    - name: Build frontend
      working-directory: ./docker_compose/frontend
      run: npm run build

    - name: Install dependencies for backend
      working-directory: ./docker_compose/backend
      run: |
        npm install

    - name: Login a Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: List frontend directory 
      run: |
        ls -la ./docker_compose/frontend/dist/frontend

    - name: Build and push frontend Docker image
      run: |
        docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest -f ./docker_compose/frontend/Dockerfile ./docker_compose/frontend 
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    - name: Build and push backend Docker image
      run: |
        docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/backend:latest -f ./docker_compose/backend/Dockerfile ./docker_compose/backend
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

    - name: Deploy containers
      run: |
        docker compose -f ./docker_compose/docker-compose.yml down 
        docker compose -f ./docker_compose/docker-compose.yml up -d

        
